#!/bin/bash 




# UPDATING REPO
sudo apt update

#INSTALL GOLANG
wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
tar -xvf go1.13.5.linux-amd64.tar.gz
sudo mv go /usr/local

export PATH=/usr/local/go/bin:$PATH:/home/syahrul/go/bin/

# INSTALL MAIN RECON TOOLS
sudo apt install chromium-browser vim ruby-full nmap netcat jq dnsutils awscli
wget https://github.com/michenriksen/aquatone/releases/download/v1.6.0/aquatone_linux_amd64_1.6.0.zip
unzip aquatone_linux_amd64_1.6.0.zip
wget https://github.com/OWASP/Amass/releases/download/v3.5.4/amass_v3.5.4_linux_amd64.zip
unzip amass_v3.5.4_linux_amd64.zip
curl https://bootstrap.pypa.io/get-pip.py -o /tmp/get-pip.py
sudo python2 /tmp/get-pip.py
sudo python3 /tmp/get-pip.py

# INSTALL LINKFINDER
cd ~
git clone https://github.com/GerbenJavado/LinkFinder.git linkfinder
cd linkfinder
sudo python setup.py install

#INSTALL GITGRABER
cd ~
git clone https://github.com/hisxo/gitGraber.git gitgraber
cd gitgraber
sudo pip3 install -r requirements.txt


#INSTALL STRUTS PWN
cd ~
git clone https://github.com/mazen160/struts-pwn_CVE-2018-11776.git struts

#INSTALL XSSTRIKE
cd ~
git clone https://github.com/s0md3v/XSStrike.git xsstrike
cd xsstrike
sudo pip3 install -r requirements.txt

#INSTALL DIRSEARCH
cd ~
git clone https://github.com/maurosoria/dirsearch.git

#INSTALL TRUFFLEHOG
sudo pip install trufflehog

#INSTALL SQLMAP
git clone https://github.com/sqlmapproject/sqlmap.git



#INSTALL DEX2JAR
cd ~
git clone https://github.com/Damian89/extended-xss-search.git
git clone https://github.com/sahruldotid/dex2jar.git
sudo wget https://raw.githubusercontent.com/iBotPeaches/Apktool/master/scripts/linux/apktool -O /usr/local/bin/apktool
sudo wget https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.4.0.jar -O /usr/local/bin/apktool.jar
sudo chmod +x /usr/local/bin/apktool*
wget https://github.com/java-decompiler/jd-gui/releases/download/v1.6.0/jd-gui-1.6.0.deb -O /tmp/jdgui.deb

#TOMNOMNOM'S TOOLS
cd ~
go get github.com/tomnomnom/waybackurls
go get -u github.com/tomnomnom/httprobe
go get -u github.com/tomnomnom/meg
go get -u github.com/tomnomnom/assetfinder


#ffuf
go get github.com/ffuf/ffuf

#crawler
go get github.com/hakluke/hakrawler

#Bash Profile
wget https://sahruldotid.github.io/bash_profile

#INSTALL WPSCAN
sudo gem install wpscan --no-rdoc --no-ri

wget https://raw.githubusercontent.com/gwen001/pentest-tools/master/smuggler.py
wget https://sahruldotid.github.io/remdup -o ~/bin/remdup
chmod +x ~/bin/remdup
rm *.zip
rm LICENSE*
rm README*
rm *tar.gz

echo "source /home/syahrul/bash_profile" >> .profile
