#!/bin/bash

sudo apt update
sudo apt install tightvncserver lubuntu-desktop
vncserver
vncserver -kill :1
cd ~
sed -i '$ d' .vnc/xstartup > .vnc/xstartup
echo "openbox &" >> .vnc/xstartup
echo "lxsession -s Lubuntu &" >> .vnc/xstartup
vncserver -geometry 1366x768
cd ~
wget https://github.com/skylot/jadx/releases/download/v0.9.0/jadx-0.9.0.zip
sudo dpkg -i /tmp/jdgui.deb
unzip jadx-0.9.0.zip
rm *zip
