#!/bin/bash

sudo apt update
sudo apt install expect tightvncserver lubuntu-desktop


/usr/bin/expect <<EOF
spawn /usr/bin/vncserver
expect "Password:"
send "syahrul\n"
expect "Verify:"
send "syahrul\n"
expect "Would you like to enter a view-only password (y/n)?"
send "n\n"
interact
EOF

vncserver
vncserver -kill :1
cd ~
sed -i '$ d' .vnc/xstartup > .vnc/xstartup
echo "openbox &" >> .vnc/xstartup
echo "lxsession -s Lubuntu &" >> .vnc/xstartup
vncserver -geometry 1366x768
cd ~
wget https://github.com/skylot/jadx/releases/download/v1.1.0/jadx-1.1.0.zip
sudo dpkg -i /tmp/jdgui.deb
unzip jadx-1.1.0.zip
rm *zip
